### ISSUE TITLE
it crash after load a exe in x32dbg

### ISSUE THREAD

**Issue by cxj98** [ThunderCls/BreakModule#1]
hello, does nobody dispute this issue? when load this plugin in x32dbg is fine, but when using x32dbg to load a exe then this plugin is crash. show result follow:

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	x32dbg.exe
  应用程序版本:	0.0.2.5
  应用程序时间戳:	58219018
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.18869
  故障模块时间戳:	556363bc
  异常代码:	0eedfade
  异常偏移:	0000c42d
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

**Comment by ThunderCls** [comment]
Ok, I'm gonna need some more details in order to detect the issue. Can you give me some more clues like what x64dbg snapshot version you're using, the kind of application you are trying to debug, etc. I need to replicate it in order to fix it

**Comment by cxj98** [comment]
OK, tried all snapshot build of x32dbg, and without use other plugins, just use this plugin to test. my pc is x64 win 7 ultimate. language pack is Chinese. load any exe file is crash.

**Comment by cxj98** [comment]
if remove this plugin is working fine.

**Comment by ThunderCls** [comment]
Mmm...could be the language pack...could you upload the files to replicate it?

**Comment by torusrxxx** [comment]
The feature of this plugin is already included in the x64dbg core. Don't use it anymore.
该插件的功能早已内置于x64dbg。无需继续使用该插件。

**Comment by rmi1974** [comment]
The plugin is simply broken. I've also encountered this when using x64dbg (x32 to be precise) under Linux/Wine.

The reason can be seen from api trace log:

```
$ pwd
/home/focht/wine-apps/x64dbg/release/x32

$ WINEDEBUG=+seh,+relay wine ./x32dbg.exe >>log.txt 2>&1
...
<attach to another process>
...
006c:Call KERNEL32.GetModuleHandleW(0268cbe8 L".\\x32dbg.dll") ret=02414f58
006c:Ret  KERNEL32.GetModuleHandleW() retval=00c10000 ret=02414f58
006c:Call KERNEL32.GetProcAddress(00c10000,0268cc02 "?SetBreakpoint@Debug@Script@@YA_NK@Z") ret=02414f5e
006c:Ret  KERNEL32.GetProcAddress() retval=00cbcb50 ret=02414f5e
006c:Call KERNEL32.GetModuleHandleW(0268cbe8 L".\\x32dbg.dll") ret=02414f74
006c:Ret  KERNEL32.GetModuleHandleW() retval=00c10000 ret=02414f74
006c:Call KERNEL32.GetProcAddress(00c10000,0268cc27 "?DeleteBreakpoint@Debug@Script@@YA_NK@Z") ret=02414f7a
006c:Ret  KERNEL32.GetProcAddress() retval=00cbc9f0 ret=02414f7a
006c:Call KERNEL32.GetModuleHandleW(0268cbe8 L".\\x32dbg.dll") ret=02414f90
006c:Ret  KERNEL32.GetModuleHandleW() retval=00c10000 ret=02414f90
006c:Call KERNEL32.GetProcAddress(00c10000,0268cc4f "?EntryFromName@Module@Script@@YAKPBD@Z") ret=02414f96
006c:Ret  KERNEL32.GetProcAddress() retval=00cbed10 ret=02414f96
006c:Call KERNEL32.MultiByteToWideChar(000004e4,00000000,0268c1ec "breakmodule.cfg",0000000f,0c17ed04,000007ff) ret=02424be4
006c:Ret  KERNEL32.MultiByteToWideChar() retval=0000000f ret=02424be4
006c:Call KERNEL32.GetFileAttributesW(02b711fc L"breakmodule.cfg") ret=02437a1e
006c:Ret  KERNEL32.GetFileAttributesW() retval=ffffffff ret=02437a1e
006c:Call KERNEL32.GetLastError() ret=02437a77
006c:Ret  KERNEL32.GetLastError() retval=00000002 ret=02437a77
006c:Call ole32.CoCreateInstance(02b7f528,00000000,00000005,0266fea8,0c17fcfc) ret=0266fe96
006c:Call ntdll.RtlInitUnicodeString(0c17f900,0c17f946 L"CLSID\\{88D96A05-F192-11D4-A65F-0040963251E5}") ret=f78619aa
006c:Ret  ntdll.RtlInitUnicodeString() retval=0000005a ret=f78619aa
006c:Call ntdll.NtOpenKey(0c17f940,00020019,0c17f908) ret=f78619ba
006c:Ret  ntdll.NtOpenKey() retval=00000000 ret=f78619ba
006c:Call ntdll.RtlNtStatusToDosError(00000000) ret=f78619c2
006c:Ret  ntdll.RtlNtStatusToDosError() retval=00000000 ret=f78619c2
006c:Call ntdll.RtlInitUnicodeString(0c17f900,f791cbd8 L"TreatAs") ret=f78619aa
006c:Ret  ntdll.RtlInitUnicodeString() retval=00000010 ret=f78619aa
006c:Call ntdll.NtOpenKey(0c17f9ec,00020019,0c17f908) ret=f78619ba
006c:Ret  ntdll.NtOpenKey() retval=c0000034 ret=f78619ba
006c:Call ntdll.RtlNtStatusToDosError(c0000034) ret=f78619c2
006c:Ret  ntdll.RtlNtStatusToDosError() retval=00000002 ret=f78619c2
006c:Call advapi32.RegCloseKey(0000017c) ret=f78644f0
006c:Ret  advapi32.RegCloseKey() retval=00000000 ret=f78644f0
006c:Call ntdll.RtlAllocateHeap(00110000,00000008,00000104) ret=f7862008
006c:Ret  ntdll.RtlAllocateHeap() retval=038a3a98 ret=f7862008
006c:err:ole:CoCreateInstanceEx apartment not initialised
006c:Ret  ole32.CoCreateInstance() retval=800401f0 ret=0266fe96
```

The plugin uses **TXMLDocument**  in OnInitDbg():

https://github.com/ThunderCls/BreakModule/blob/00ca133f66cf74e3a6b053b3633ed4e0597aab9c/BreakModule.cpp#L151

By default, TXMLDocument uses MSXML on Windows which is if course COM-based (inproc server).
Developers need to make sure that the thread has initialized COM with CoInitialize/Ex() before creating the TXMLDocument object. This was obviously is not done. There is no single CoInitialize/Ex() call during startup of x64dbg/x32dbg in neither the main thread nor worker threads -> plugin broken.

**Comment by ThunderCls** [comment]
This plugin is deprecated and won't be updated anymore. x64dbg has already included this functionality in its core.
